[book]
authors = ["The Funkin' Crew Inc.", "EliteMasterEric", "moltenman5"]
language = "en"
multilingual = false
src = "src"
title = "Friday Night Funkin' Modding Documentation EXTENDED"


[output.html]
git-repository-url = "https://github.com/moltenman5/better-fnf-modding-docs/tree/main/"
edit-url-template = "https://github.com/moltenman5/better-fnf-modding-docs/edit/main/{path}"
